### ISSUE TITLE
#TK09 Generar componente header

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#11]
Generar componente header dentro del módulo common

**Comment by Noobuyer** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Modelo de administración de bienes raíces</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <header>
      <nav>
        <ul>
          <li><a href="#home">Inicio</a></li>
          <li><a href="#propiedades">Propiedades</a></li>
          <li><a href="#agentes">Agentes inmobiliarios</a></li>
          <li><a href="#contacto">Contacto</a></li>
        </ul>
      </nav>
    </header>
    <main>
      <section id="home">
        <h1>Bienvenido al modelo de administración de bienes raíces</h1>
        <p>Esta es una plataforma en línea para buscar, comprar y vender propiedades de bienes raíces.</p>
        <a href="#propiedades">Explorar propiedades</a>
      </section>
      <section id="propiedades">
        <h2>Propiedades</h2>
        <ul>
          <li>
            <h3>Propiedad 1</h3>
            <img src="propiedad1.jpg" alt="Propiedad 1">
            <p>Descripción de la propiedad 1.</p>
          </li>
          <li>
            <h3>Propiedad 2</h3>
            <img src="propiedad2.jpg" alt="Propiedad 2">
            <p>Descripción de la propiedad 2.</p>
          </li>
          <li>
            <h3>Propiedad 3</h3>
            <img src="propiedad3.jpg" alt="Propiedad 3">
            <p>Descripción de la propiedad 3.</p>
          </li>
        </ul>
      </section>
      <section id="agentes">
        <h2>Agentes inmobiliarios</h2>
        <ul>
          <li>
            <h3>Agente 1</h3>
            <img src="agente1.jpg" alt="Agente 1">
            <p>Descripción del agente 1.</p>
          </li>
          <li>
            <h3>Agente 2</h3>
            <img src="agente2.jpg" alt="Agente 2">
            <p>Descripción del agente 2.</p>
          </li>
          <li>
            <h3>Agente 3</h3>
            <img src="agente3.jpg" alt="Agente 3">
            <p>Descripción del agente 3.</p>
          </li>
        </ul>
      </section>
      <section id="contacto">
        <h2>Contacto</h2>
        <form>
          <label for="nombre">Nombre:</label>
          <input type="text" id="nombre" name="nombre" required>
          <label for="email">Email:</label>
          <input type="email" id="email" name="email" required>
        </form>
      </section>
    </main>
  </body>
</html>
