### ISSUE TITLE
#TK10 Generar componente nav

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#12]

**Comment by Noobuyer** [comment]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Modelo de administración de bienes raíces</title>
    <link rel="stylesheet" href="styles.css">
  </head>
  <body>
    <header>
      <nav></nav>
    </header>
    <main>
      <section id="home">
        <h1>Bienvenido al modelo de administración de bienes raíces</h1>
        <p>Esta es una plataforma en línea para buscar, comprar y vender propiedades de bienes raíces.</p>
        <a href="#propiedades">Explorar propiedades</a>
      </section>
      <section id="propiedades">
        <h2>Propiedades</h2>
        <ul>
          <li>
            <h3>Propiedad 1</h3>
            <img src="propiedad1.jpg" alt="Propiedad 1">
            <p>Descripción de la propiedad 1.</p>
          </li>
          <li>
            <h3>Propiedad 2</h3>
            <img src="propiedad2.jpg" alt="Propiedad 2">
            <p>Descripción de la propiedad 2.</p>
          </li>
          <li>
            <h3>Propiedad 3</h3>
            <img src="propiedad3.jpg" alt="Propiedad 3">
            <p>Descripción de la propiedad 3.</p>
          </li>
        </ul>
      </section>
      <section id="agentes">
        <h2>Agentes inmobiliarios</h2>
        <ul>
          <li>
            <h3>Agente 1</h3>
            <img src="agente1.jpg" alt="Agente 1">
            <p>Descripción del agente 1.</p>
          </li>
          <li>
            <h3>Agente 2</h3>
            <img src="agente2.jpg" alt="Agente 2">
            <p>Descri

**Comment by mariquenaallosa** [comment]
eac44babb1745d1b9772b1a7ee972e00bd24d275
