### ISSUE TITLE
#TK21 Editar componente users

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#37]
El componente se encuentra generado en el proyecto. 
Hay que copiar el código HTML y CSS del proyecto anterior

**Comment by Noobuyer** [comment]
Etiquetas no cerradas: Algunas etiquetas HTML no están cerradas correctamente. Por ejemplo, en la línea 17 falta cerrar la etiqueta <div class="sidebar-logo"> y en la línea 63 falta cerrar la etiqueta <div class="col-sm-12 col-lg-6 mt-">.

IDs duplicados: En varias partes del código, se están utilizando los mismos IDs para diferentes elementos. Por ejemplo, en las líneas 67, 83 y 99 se repite el ID "navbarDropdown" en los elementos de desplegable. Los IDs deben ser únicos en un documento HTML.

Uso de etiquetas <h6> y <h5> dentro de enlaces <a>: En las líneas 14 y 37, se están utilizando etiquetas de encabezado <h6> y <h5> dentro de elementos <a>. Esto no es semánticamente correcto y podría causar problemas de accesibilidad. Se recomienda utilizar las etiquetas de encabezado de forma independiente y, si es necesario, aplicar estilos CSS para lograr la apariencia deseada.
