### ISSUE TITLE
#TK22 Ruteo

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#38]

**Comment by Noobuyer** [comment]
Primero, asegúrate de que tienes instalada la CLI de Angular. Puedes verificarlo ejecutando el siguiente comando en tu terminal:

Copy code
ng version
A continuación, crea un nuevo proyecto de Angular si aún no lo has hecho:

arduino
Copy code
ng new nombre-del-proyecto
Cambia al directorio del proyecto:

bash
Copy code
cd nombre-del-proyecto
Crea un nuevo componente para la página de inicio (home) y otros componentes adicionales que necesites:

arduino
Copy code
ng generate component home
ng generate component catalog
ng generate component contact
Abre el archivo app-routing.module.ts ubicado en la carpeta src/app. Aquí es donde configuraremos nuestras rutas.

Importa los componentes que deseas enrutarse. En este ejemplo, importaremos los componentes Home, Catalog y Contact:

typescript
Copy code
import { HomeComponent } from './home/home.component';
import { CatalogComponent } from './catalog/catalog.component';
import { ContactComponent } from './contact/contact.component';
Define las rutas para tus componentes en el arreglo routes:

typescript
Copy code
const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'catalog', component: CatalogComponent },
  { path: 'contact', component: ContactComponent }
];
Exporta las rutas utilizando RouterModule.forRoot():

typescript
Copy code
@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
Ahora, abre el archivo app.component.html ubicado en la carpeta src/app. Reemplaza su contenido con el siguiente código:

html
Copy code
<router-outlet></router-outlet>
Por último, abre el archivo app.module.ts ubicado en la carpeta src/app. Importa y agrega AppRoutingModule a la lista de imports:

typescript
Copy code
import { AppRoutingModule } from './app-routing.module';

@NgModule({
  declarations: [
    // ...
  ],
  imports: [
    // ...
    AppRoutingModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
Con estos pasos, has configurado el enrutamiento de componentes en tu aplicación Angular. Ahora, puedes navegar a las rutas que has definido, por ejemplo, /catalog o /contact, y se mostrarán los componentes correspondientes en el <router-outlet> del archivo app.component.html.

Recuerda que también puedes configurar rutas anidadas, parámetros de ruta, rutas con comodines, etc., según tus necesidades específicas. Para obtener más información sobre el enrutamiento en Angular, puedes consultar la documentación oficial: https://angular.io/guide/router
