### ISSUE TITLE
#TK23 Solucionar importación de íconos para el sitio

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#39]

**Comment by Noobuyer** [comment]
Para solucionar la importación de íconos en tu sitio web, puedes seguir estos pasos:

1. Verifica la ruta de importación: Asegúrate de que estés importando los íconos correctamente en tu código. Revisa la ruta de importación para asegurarte de que sea correcta y esté apuntando al archivo de íconos adecuado.

2. Verifica la disponibilidad de los íconos: Asegúrate de que los archivos de íconos que estás intentando importar estén presentes en la ubicación especificada. Verifica si los íconos se encuentran en la carpeta correcta y si tienen el nombre de archivo correcto.

3. Verifica los permisos de acceso: Comprueba los permisos de acceso de los archivos de íconos y asegúrate de que el servidor web tenga los permisos adecuados para acceder a ellos. Si los permisos no son correctos, puedes ajustarlos para garantizar que los archivos sean accesibles.

4. Verifica la conexión de red: Asegúrate de tener una conexión de red estable y funcional. Si hay problemas de conectividad, es posible que los íconos no se carguen correctamente. Intenta cargar otros recursos, como imágenes, para asegurarte de que la conexión de red esté funcionando correctamente.

5. Limpia la caché del navegador: Si has realizado cambios en la importación de los íconos, es posible que el navegador tenga una versión en caché del sitio web que impida que los cambios se reflejen. Intenta limpiar la caché del navegador o prueba a abrir el sitio en una ventana de navegación privada/incógnito para ver si los íconos se cargan correctamente.

6. Utiliza herramientas de desarrollo: Utiliza las herramientas de desarrollo del navegador para verificar si hay errores en la carga de los íconos. Abre la consola del navegador (generalmente presionando F12) y observa si hay algún mensaje de error relacionado con la importación de los íconos.

Al seguir estos pasos, deberías poder solucionar los problemas de importación de íconos en tu sitio web.

**Comment by mariquenaallosa** [comment]
Eso no soluciona los íconos

**Comment by mariquenaallosa** [comment]
Incorporación de Bootstrap Icons 00d7f19f51f289d9c42890fd6b37def06e525e89
Para usar iconos  en el sitio sacar de acá : https://icons.getbootstrap.com/
