### ISSUE TITLE
#TK03 Definir módulos y componentes a utilizar

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#4]

**Comment by Noobuyer** [comment]
1. Registro e inicio de sesión: Permite que los usuarios se registren e inicien sesión en la aplicación para acceder a sus funcionalidades.

2. Búsqueda de propiedades: Permite a los usuarios buscar propiedades por tipo, ubicación, precio, características, etc.

3. Visualización de propiedades: Los usuarios pueden ver imágenes, videos y descripciones detalladas de las propiedades.

4. Favoritos: Los usuarios pueden marcar propiedades como favoritas para acceder a ellas más tarde.

5. Mapas y ubicaciones: Un módulo que muestra la ubicación de las propiedades en un mapa y proporciona direcciones y rutas.

6. Contacto con agentes inmobiliarios: Los usuarios pueden contactar con agentes inmobiliarios para solicitar información adicional o programar visitas.

8. Publicación de propiedades: Un panel de administración para los agentes inmobiliarios para publicar nuevas propiedades, editar la información de las propiedades existentes y actualizar el estado de las propiedades vendidas.

9. Comentarios y calificaciones: Los usuarios pueden dejar comentarios y calificaciones de las propiedades y los agentes inmobiliarios.

10. Notificaciones: Un módulo que envía notificaciones a los usuarios sobre nuevas propiedades que puedan ser de su interés, así como actualizaciones sobre las propiedades marcadas como favoritas.
