### ISSUE TITLE
#TK25 Establecer modelo de BD en Django

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#41]

**Comment by Noobuyer** [comment]
Crea una nueva aplicación en Django utilizando el comando python manage.py startapp nombre_de_la_app.

En el archivo models.py de tu aplicación, define los modelos necesarios para representar los elementos de tu inmobiliaria. Aquí hay algunos ejemplos de posibles modelos:

from django.db import models

class Propiedad(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    habitaciones = models.IntegerField()
    banos = models.IntegerField()
    metros_cuadrados = models.DecimalField(max_digits=10, decimal_places=2)
    direccion = models.CharField(max_length=200)
    imagen_principal = models.ImageField(upload_to='propiedades/')
    fecha_publicacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo

class Agente(models.Model):
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    email = models.EmailField()
    foto = models.ImageField(upload_to='agentes/')

    def __str__(self):
        return self.nombre


Para establecer un modelo de base de datos en Django para una inmobiliaria, puedes considerar los siguientes pasos:

Crea una nueva aplicación en Django utilizando el comando python manage.py startapp nombre_de_la_app.

En el archivo models.py de tu aplicación, define los modelos necesarios para representar los elementos de tu inmobiliaria. Aquí hay algunos ejemplos de posibles modelos:

python
Copy code
from django.db import models

class Propiedad(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    habitaciones = models.IntegerField()
    banos = models.IntegerField()
    metros_cuadrados = models.DecimalField(max_digits=10, decimal_places=2)
    direccion = models.CharField(max_length=200)
    imagen_principal = models.ImageField(upload_to='propiedades/')
    fecha_publicacion = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.titulo

class Agente(models.Model):
    nombre = models.CharField(max_length=100)
    telefono = models.CharField(max_length=20)
    email = models.EmailField()
    foto = models.ImageField(upload_to='agentes/')

    def __str__(self):
        return self.nombre
En este ejemplo, hemos definido dos modelos: "Propiedad" y "Agente". El modelo "Propiedad" contiene información sobre las propiedades en venta, como título, descripción, precio, número de habitaciones, número de baños, metros cuadrados, dirección, imagen principal y fecha de publicación. El modelo "Agente" representa a los agentes de la inmobiliaria y contiene información como nombre, teléfono, correo electrónico y foto.

Ejecuta el comando python manage.py makemigrations para generar las migraciones basadas en los modelos que has definido.

Aplica las migraciones a la base de datos utilizando el comando python manage.py migrate.

Una vez completados estos pasos, tus modelos estarán configurados y podrás utilizarlos para realizar consultas y manipular los datos de tu inmobiliaria a través de las API de Django ORM.
