### ISSUE TITLE
#TK08 Backend - Diseño físico - Diagrama de Clases y Casos de Uso

### ISSUE THREAD

**Issue by mariquenaallosa** [mariquenaallosa/ProyectoISPC#9]
Verificar si los Diseños presentados [en la wiki](https://github.com/mariquenaallosa/ProyectoISPC/wiki/Estado-del-proyecto) se acoplan a los nuevos objetivos del proyecto

-  **Diseño Físico** que es el script legible de la DB en MySQL.

-  **Diagrama de Clases y Casos de Uso**  para facilitar el modelado en POO.

**Comment by etexter28** [comment]
[bd_bienes_raices.zip](https://github.com/mariquenaallosa/ProyectoISPC/files/11413517/bd_bienes_raices.zip)

**Comment by mariquenaallosa** [comment]
Aplicar los cambio que se hablaron en la Reunión
